services:
  hewalex2mqtt:
    container_name: hewalex2mqtt
    build:
      context: ./hewalex2mqtt
      network: host
    restart: unless-stopped
    network_mode: host
    env_file:
      - '.env.hewalex2mqtt'
    volumes:
      - /hewagate:/hewagate