# Hewalex heatpump sensors
- name: Date
  state_topic: heatpump/hewalex/date
  unique_id: heatpump_hewalex_date
  icon: mdi:calendar
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Time
  state_topic: heatpump/hewalex/time
  unique_id: heatpump_hewalex_time
  icon: mdi:clock
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Ambient Temperature (T1)
  state_topic: heatpump/hewalex/T1
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t1
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Bottom Tank Temperature (T2)
  state_topic: heatpump/hewalex/T2
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t2
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Top Tank Temperature (T3)
  state_topic: heatpump/hewalex/T3
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t3
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Heat Pump Water Inlet Temperature (T6)
  state_topic: heatpump/hewalex/T6
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t6
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Heat Pump Water Outlet Temperature (T7)
  state_topic: heatpump/hewalex/T7
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t7
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Evaporator Temperature (T8)
  state_topic: heatpump/hewalex/T8
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t8
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Pre Compressor Temperature (T9)
  state_topic: heatpump/hewalex/T9
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t9
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Post Compressor Temperature (T10)
  state_topic: heatpump/hewalex/T10
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_t10
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Tap Water Temperature Setpoint
  state_topic: heatpump/hewalex/TapWaterTemp
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_tapwater
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Tap Water Hysteresis Setpoint
  state_topic: heatpump/hewalex/TapWaterHysteresis
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  icon: mdi:thermometer
  unique_id: hewalex_heatpump_hysteresis
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Heat Pump Circulation Pump
  state_topic: heatpump/hewalex/WaterPumpON
  unique_id: hewalex_heatpump_waterpump
  value_template: >-
    {% if value == True %}
        On
    {% else %}
        Off
    {% endif %}
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Fan
  state_topic: heatpump/hewalex/FanON
  unique_id: hewalex_heatpump_fan
  value_template: >-
    {% if value == True %}
        On
    {% else %}
        Off
    {% endif %}
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Heat Pump Expansion Valve
  state_topic: heatpump/hewalex/EV1
  unit_of_measurement: -/-
  unique_id: hewalex_heatpump_ev1
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Operational Status
  state_topic: heatpump/hewalex/WaitingStatus
  unique_id: heatpump_hewalex_waitingstatus
  icon: mdi:timer-pause
  value_template: >-
    {% if value == "0" %}
        Available
    {% elif value == "2" %}
        Disabled
    {% elif value == "32" %}
        Stopped (waiting restart)
    {% elif value == "64" %}
        Low COP
    {% else %}
       Unknown ({{ value }})
    {% endif %}
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Restart Timer
  state_topic: heatpump/hewalex/WaitingTimer
  unique_id: heatpump_hewalex_waitingtimer
  state_class: measurement
  icon: mdi:timer-pause
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Installation Scheme
  #command_topic: heatpump/hewalex/Command/InstallationScheme
  state_topic: heatpump/hewalex/InstallationScheme
  unique_id: heatpump_hewalex_installationscheme
  icon: mdi:format-list-numbered-rtl
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Time Program Heat Pump Weekdays
  #command_topic: heatpump/hewalex/Command/TimeProgramHPM-F
  state_topic: heatpump/hewalex/TimeProgramHPM-F
  unique_id: heatpump_hewalex_timeprogramhpm-f
  state_class: measurement
  icon: mdi:calendar-week
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Time Program Heat Pump Saturday
  #command_topic: heatpump/hewalex/Command/TimeProgramHPSat
  state_topic: heatpump/hewalex/TimeProgramHPSat
  unique_id: heatpump_hewalex_timeprogramhpsat
  state_class: measurement
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Time Program Heat Pump Sunday
  #command_topic: heatpump/hewalex/Command/TimeProgramHPSun
  state_topic: heatpump/hewalex/TimeProgramHPSun
  unique_id: heatpump_hewalex_timeprogramhpsun
  state_class: measurement
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Electric Heater (E) Time Program Weekdays
  #command_topic: heatpump/hewalex/Command/HeaterETimeProgramM-F
  state_topic: heatpump/hewalex/HeaterETimeProgramM-F
  unique_id: heatpump_hewalex_heateretimeprogramm-f
  icon: mdi:calendar-week
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Electric Heater (E) Time Program Saturday
  #command_topic: heatpump/hewalex/Command/HeaterETimeProgramSat
  state_topic: heatpump/hewalex/HeaterETimeProgramSat
  unique_id: heatpump_hewalex_heateretimeprogramsat
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Electric Heater (E) Time Program Sunday
  #command_topic: heatpump/hewalex/Command/HeaterETimeProgramSun
  state_topic: heatpump/hewalex/HeaterETimeProgramSun
  unique_id: heatpump_hewalex_heateretimeprogramsun
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Electric Heater (P) Time Program Weekdays
  #command_topic: heatpump/hewalex/Command/HeaterPTimeProgramM-F
  state_topic: heatpump/hewalex/HeaterPTimeProgramM-F
  unique_id: heatpump_hewalex_heaterptimeprogramm-f
  icon: mdi:calendar-week
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Electric Heater (P) Time Program Saturday
  #command_topic: heatpump/hewalex/Command/HeaterPTimeProgramSat
  state_topic: heatpump/hewalex/HeaterPTimeProgramSat
  unique_id: heatpump_hewalex_heaterptimeprogramsat
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Electric Heater (P) Time Program Sunday
  #command_topic: heatpump/hewalex/Command/HeaterPTimeProgramSun
  state_topic: heatpump/hewalex/HeaterPTimeProgramSun
  unique_id: heatpump_hewalex_heaterptimeprogramsun
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Tap Water Circulation Pump Time Program Weekdays
  #command_topic: heatpump/hewalex/Command/CirculationPumpTimeProgramM-F
  state_topic: heatpump/hewalex/CirculationPumpTimeProgramM-F
  unique_id: heatpump_hewalex_circulationpumptimeprogramm-f
  icon: mdi:calendar-week
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Tap Water Circulation Pump Time Program Saturday
  #command_topic: heatpump/hewalex/Command/CirculationPumpTimeProgramSat
  state_topic: heatpump/hewalex/CirculationPumpTimeProgramSat
  unique_id: heatpump_hewalex_circulationpumptimeprogramsat
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Tap Water Circulation Pump Time Program Sunday
  #command_topic: heatpump/hewalex/Command/CirculationPumpTimeProgramSun
  state_topic: heatpump/hewalex/CirculationPumpTimeProgramSun
  unique_id: heatpump_hewalex_circulationpumptimeprogramsun
  icon: mdi:calendar-weekend
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex