- name: Enable Heatpump
  command_topic: heatpump/hewalex/Command/HeatPumpEnabled
  state_topic: heatpump/hewalex/HeatPumpEnabled
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: hewalex_heatpump_heatpumpenabled
  icon: mdi:heat-pump
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Enable External Controller
  command_topic: heatpump/hewalex/Command/ExtControllerHPOFF
  state_topic: heatpump/hewalex/ExtControllerHPOFF
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: hewalex_heatpump_extcontrollerhpoff
  icon: mdi:power-off
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Anti-freezing
# It is a protection against the occurrence of sub-zero temperature in room,
# where heat pump is installed. In case of too low temperature indicated by
# the T6 sensor, circulating pump will switch on and start pumping water
# between the tank and heat pump, so as to avoid pipeline or condenser
# defrosting.
  command_topic: heatpump/hewalex/Command/AntiFreezingEnabled
  state_topic: heatpump/hewalex/AntiFreezingEnabled
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: hewalex_heatpump_antifreezingenabled
  icon: mdi:snowflake-off
  device:
    identifiers:
      - heatpump_hewalex
    name: Hewalex Heat Pump
- name: Electric Heater (E)
# External control unit
# Depending on the selected diagram, we are able to define, which
# appliances are to be operated by the external control unit. For
# example, if we set heat pump deactivation to NO, even after bridge
# opening the heat pump will be working in compliance with the factory
# controller.
  command_topic: heatpump/hewalex/Command/HeaterEEnabled
  state_topic: heatpump/hewalex/HeaterEEnabled
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_heatereenabled
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Block Electric Heater (E) When Heat Pump Is On
  command_topic: heatpump/hewalex/Command/HeaterEBlocked
  state_topic: heatpump/hewalex/HeaterEBlocked
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_heatereblocked
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Electric Heater (P)
  command_topic: heatpump/hewalex/Command/HeaterPEnabled
  state_topic: heatpump/hewalex/HeaterPEnabled
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_heaterpenabled
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Block Electric Heater (P) When Heat Pump Is On
  command_topic: heatpump/hewalex/Command/HeaterPBlocked
  state_topic: heatpump/hewalex/HeaterPBlocked
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_heaterpblocked
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Boiler Pump Priority
  command_topic: heatpump/hewalex/Command/BoilerPumpPriority
  state_topic: heatpump/hewalex/BoilerPumpPriority
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_boilerpumppriority
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Anti-Legionella
  command_topic: heatpump/hewalex/Command/AntiLegionellaEnabled
  state_topic: heatpump/hewalex/AntiLegionellaEnabled
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_antilegionellaenabled
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Use Electric Heater (E) for Anti-Legionella
  command_topic: heatpump/hewalex/Command/AntiLegionellaUseHeaterE
  state_topic: heatpump/hewalex/AntiLegionellaUseHeaterE
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_antilegionellauseheatere
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Use Electric Heater (P) for Anti-Legionella
  command_topic: heatpump/hewalex/Command/AntiLegionellaUseHeaterP
  state_topic: heatpump/hewalex/AntiLegionellaUseHeaterP
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_antilegionellauseheaterp
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Enable External Control for Electric Heater (E)
  command_topic: heatpump/hewalex/Command/ExtControllerHeaterEOFF
  state_topic: heatpump/hewalex/ExtControllerHeaterEOFF
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_extcontrollerheatereoff
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Enable External Control for Solid Fuel Pump
  command_topic: heatpump/hewalex/Command/ExtControllerPumpFOFF
  state_topic: heatpump/hewalex/ExtControllerPumpFOFF
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_extcontrollerpumpfoff
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex
- name: Enable External Control for Electric Heater (P)
  command_topic: heatpump/hewalex/Command/ExtControllerHeaterPOFF
  state_topic: heatpump/hewalex/ExtControllerHeaterPOFF
  payload_on: True
  payload_off: False
  state_on: True
  state_off: False
  unique_id: heatpump_hewalex_extcontrollerheaterpoff
  device:
    name: Hewalex Heat Pump
    identifiers:
    - heatpump_hewalex